//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FranchiseRate()
        {
            this.Parcels = new HashSet<Parcel>();
        }
    
        public int FranchiseId { get; set; }
        public string Name { get; set; }
        public Nullable<byte> DeliveryType { get; set; }
        public Nullable<decimal> RatePerKm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcel> Parcels { get; set; }
    }
}
