//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingAddress
    {
        public int ShippingId { get; set; }
        public int UserId { get; set; }
        public int ParecelId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> Phone { get; set; }
    
        public virtual Parcel Parcel { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
